version: "3.9"
services:
  hello:
    image: jwilder/whoami
    deploy:
      mode: replicated
      replicas: 1
      labels:
        "balancer.enable": "true"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - target: 8080
        published: 8080
        mode: host
    deploy:
      mode: global

  prometheus:
    image: prom/prometheus:v2.12.0
    command:
      [
        "--storage.tsdb.retention.size=1GB",
        "--config.file=/etc/prometheus/prometheus.yml",
        "--web.console.libraries=/etc/prometheus/console_libraries",
        "--web.console.templates=/etc/prometheus/consoles",
        "--web.enable-lifecycle",
      ]
    ports:
      - target: 9090
        published: 9090
        mode: host
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

configs:
  prometheus_config:
    file: ./prometheus.yml
