name: Backend CI
on:
  push:
    branches:
      - "*"
    paths:
      - "packages/backend/**"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}-backend

jobs:
  build:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        working-directory: packages/backend
        run: npm ci

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3.6.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long,enable=${{ github.ref_type != 'tag' }}
            type=ref,event=branch
            type=semver,pattern={{raw}},enable=${{ github.ref_type == 'tag' }}
            type=raw,value=latest,enable=${{ github.event.ref =='refs/heads/master'}}
          flavor: latest=false

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v2
        with:
          context: packages/backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}